### ISSUE TITLE
Errors When Using

### ISSUE THREAD

**Issue by ghost** [warren-bank/node-hls-downloader-tubitv#2]
I ran npm install --global @warren-bank/node-hls-downloader-tubitv

And it works but how exactly do I use it because I run tubidl in the command promp in the directory and it isn't recognized.

Do I have to run the .bat or .sh files in the tests folder?

**Comment by ghost** [comment]
Update Fixed That Issue but now when I run tubidl -mc 5 -u and than my url it gives me this error.

Error: Error: parsing JSON metadata for series video stream in server response at URL: 'https://tubitv.com/series/4718/lego-ninjago-masters-of-spinjitzu'
    at process_html (C:\Users\Admin\AppData\Roaming\npm\node_modules\@warren-bank\node-hls-downloader-tubitv\lib\process_cli.js:90:13)
    at process_url (C:\Users\Admin\AppData\Roaming\npm\node_modules\@warren-bank\node-hls-downloader-tubitv\lib\process_cli.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process_argv (C:\Users\Admin\AppData\Roaming\npm\node_modules\@warren-bank\node-hls-downloader-tubitv\lib\process_cli.js:337:7)

**Comment by warren-bank** [comment]
that was my bad..
* TubiTV made a small change to the JSON data returned by their API
  - well.. it's not actually JSON
  - it's javascript that they must run through `eval()`
  - I refuse to do that.. so I need to make minor corrections to be able to run it through `JSON.parse()`
* in mid- December of 2021, TubiTV added a timestamp field that is assigned a value using the `new Date()` constructor
  - I added a fix almost same day to my [TubiTV userscript](https://github.com/warren-bank/crx-Tubi-TV) at [`v2.0.5`](https://github.com/warren-bank/crx-Tubi-TV/commits/webmonkey-userscript/es5)
  - forgot to update this repo, since I haven't used it in years
* [`v1.3.3`](https://github.com/warren-bank/node-hls-downloader-tubitv/releases/tag/v1.3.3) fixes this error
  - thanks for reporting!

**Comment by warren-bank** [comment]
PS:

1) update your globally installed package:
   ```bash
     npm update --global @warren-bank/node-hls-downloader-tubitv
   ```
2) confirm that you're now running the correct version (ie: '1.3.3')
   ```bash
     tubidl --version
   ```
3) ???
4) profit..
   ```bash
     tubidl -mc 5 -u "https://tubitv.com/series/4718/lego-ninjago-masters-of-spinjitzu"
   ```
